version: '3.3'
services:
  frontend:
    image: yo1k/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:13.0-alpine
    volumes:
      - foodgram_db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: yo1k/api_foodgram:latest
    restart: always
    command: >
      bash -c "
        python manage.py collectstatic --noinput &&
        python manage.py migrate && 
        gunicorn api_foodgram.wsgi:application --bind 0:8000
      "
    volumes:
      - ../data:/data/
      - foodgram_media:/app/media/
      - foodgram_static:/app/static/
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - foodgram_media:/var/html/media/
      - foodgram_static:/var/html/static/
    depends_on:
      - frontend
      - web

volumes:
  foodgram_db_data:
  foodgram_media:
  foodgram_static:
