# Generated by Django 3.2.18 on 2023-02-27 11:38

from django.db import (
    migrations,
    models
)


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_ingredient_unique_measurement_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='empty_image', upload_to='recipes/'),
            preserve_default=False,
        ),
    ]
