# Generated by Django 3.2.18 on 2023-02-28 16:22

import django.utils.timezone
from django.db import (
    migrations,
    models
)


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='publication date'),
            preserve_default=False,
        ),
    ]
