# Generated by Django 3.2.18 on 2023-03-05 08:36

import sys

from django.core.exceptions import ValidationError
from django.db import migrations

DEFAULT_TAGS = [
    {
        'color': '#eb4634',
        'name': 'Завтрак',
        'slug': 'breakfast',
    },
    {
        'color': '#ebd634',
        'name': 'Обед',
        'slug': 'lunch',
    },
    {
        'color': '#7aeb34',
        'name': 'Ужин',
        'slug': 'dinner',
    },
    {
        'color': '#9b34eb',
        'name': 'Коктейли',
        'slug': 'cocktails',
    },
    {
        'color': '#349ceb',
        'name': 'Закуски',
        'slug': 'snacks',
    },
]


def add_tags(apps, schema_editor):
    Tag = apps.get_model('recipes', 'Tag')
    for tag in DEFAULT_TAGS:
        new_tag = Tag(**tag)
        try:
            new_tag.full_clean()
        except ValidationError as e:
            print(e, file=sys.stderr)
        new_tag.save()


def remove_tags(apps, schema_editor):
    Tag = apps.get_model('recipes', 'Tag')
    slug_list = [tag['slug'] for tag in DEFAULT_TAGS.items()]
    Tag.objects.filter(slug__in=slug_list).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20230228_1622'),
    ]

    operations = [
        migrations.RunPython(add_tags, remove_tags)
    ]
