# Generated by Django 3.2.18 on 2023-03-05 09:13

import json
import sys

from django.conf import settings
from django.db import migrations

CSV_DIR = settings.BASE_DIR.parent / 'data'
INGREDIENTS_FPATH = CSV_DIR / 'ingredients.json'


def get_default_ingredients(fpath):
    with open(fpath) as json_file:
        return json.load(json_file)

def add_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('recipes', 'Ingredient')
    data = get_default_ingredients(INGREDIENTS_FPATH)
    try:
        Ingredient.objects.bulk_create(
            [Ingredient(**ingredient) for ingredient in data],
            ignore_conflicts=True
        )
    except Exception as e:
        print(e, file=sys.stderr)


def remove_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('recipes', 'Ingredient')
    data = get_default_ingredients(INGREDIENTS_FPATH)
    for ingredient in data:
        Ingredient.objects.filter(**ingredient).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_add_tags'),
    ]

    operations = [
        migrations.RunPython(add_ingredients, remove_ingredients)
    ]
